config/routes.rb
Bbs::Application.routes.draw do

  resources :themes do
    resources :comments
  end
  

  match ':controller(/:action(/:id))(.:format)'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :theme
#  validates_presence_of :c_orner, :c_title, :c_body
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  has_many :comments
  validates_presence_of :orner, :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @theme_title = Theme.find(params[:theme_id])
    puts 99999999999999999999999999999999999999
    puts params
    puts 99999999999999999999999999999999999999

#    @comments = Comment.all
  end
  
  def show
#    @theme = Theme.find_all_by_theme_id(params[:id])
#    @themes = Theme.all

#    @comments = Comment.find_all_by_theme_id(params[:id])
#    @comments = Comment.all
    @all_comments = Comment.all #for_test
#    @com = @theme.comments

#    @comments = Comment.find_by_theme_id(params[:id])


  end

  def new
    @comment = Comment.new
    @theme_id = params[:id] #this is invalid
#    p params
#    @id = params[:theme_id]
#    puts 22222222222222222222222222
#    puts @theme_id
#    puts @comment
#    puts 
#    puts 22222222222222222222222222
  end

  def create
    @comment = Comment.new(params[:comment])
    logger.debug "------------------debug start---------------------"
    logger.debug "params ="
    logger.debug params

    logger.debug "params[:comment]="
    logger.debug params[:comment]

    logger.debug "@comment="
    logger.debug @comment

    logger.debug "@comment.id="
    logger.debug @comment.id
   
    logger.debug "comment.theme_id="    
    logger.debug @comment.theme_id

    logger.debug "------------------debug end---------------------"

    @comment.save
    redirect_to :controller => 'themes', :action => 'show', :id => params[:theme_id]

#format.html { redirect_to(:action => 'show', :id => params[:theme_id])}


#    redirect_to :url => "/themes/#{params[:theme_id]}/"

#    respond_to do |format|
#      if @comment.update_attributes(params[:comment])
#        format.html { redirect_to "www.google.com", notice: 'Theme was successfully updated.' }
#        format.json { head :no_content }
#      else
#        format.html { render action: :new }
#        format.json { render json: @comment.errors, status: :unprocessable_entity }
#      end
#    end
    
#    if @comment.save
#      redirect_to controller: :themes, action: :show, id: @comment.theme.id
#    else
#      redirect_to controller: :comments, action: :new
#    end

#   redirect_to theme_path(@comment.theme.id)
#   redirect_to "http://www.google.com"

  end

  def edit
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  def index
    @themes = Theme.all
  end

  def show
    @theme = Theme.find(params[:id])
#    @comments = Comment.find_all_by_theme_id(params[:id]) #check maybe params => @theme.id
#    @themes = Theme.find_all_by_id(@theme.id)
#    @num = params[:id]
#    @comments = Comment.find_all_by_theme_id("1")
#     @comments = Comment.all
    @comments = Comment.find(:all, :conditions => ["theme_id = :id",{:id => @theme.id}])
  end

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(params[:theme])

    respond_to do |format|
      if @theme.update_attributes(params[:theme])
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end 



#    if @theme.save
#      redirect_to (url_for(action: "index"))
#    else
#      redirect_to (url_for(action: "new"))
#    end
#  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/comments/create.html.erb
hogehoe

<%= link_to "next", action: :show %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h2>Input your Comment</h2>

<%
=begin
%>

<% if @comment.errors.any? %>
  <div>
    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- <% form_for (@comment) , url: {action: 'create'} do |f| %> -->
<%= form_for(@comment)  do |f| %>
  <table>
    <tr><td>Your Name : </td><td><%= f.text_field :c_orner, { size: 30 } %></td></tr>
    <tr><td>Subject : </td><td><%= f.text_field :c_title , { size: 30 } %></td></tr>
    <tr><td>Cooment : </td><td><%= f.text_area :c_body , { cols: 50, rows: 5 } %></td></tr>
    <%= f.hidden_field :theme_id, :value => "#{@comment.theme_id}" %>
<!--     <%= hidden_field_tag(:parent_id, "5") %>   -->

<tr><td></td><td><%= f.submit %></td></tr>
  </table>
<% end %>

<% # form_for (@comment, {:action => "create"}) do |f| %>
<%= form_for(@comment), {action: :create} do |f| %>
<%= form_for(@comment):url => {:action => 'create'} do |f| %>
<% #hidden_field_tag(:theme_id , @comment.theme_id) %>


<%= form_for(@comment, :url=>theme_comments_path(@comment.theme_id)) do |f| %>
  <table>
    <tr><td>Your Name : </td><td><%= f.text_field :c_orner, { size: 30 } %></td></tr>
    <tr><td>Subject : </td><td><%= f.text_field :c_title , { size: 30 } %></td></tr>
    <tr><td>Cooment : </td><td><%= f.text_area :c_body , { cols: 50, rows: 5 } %></td></tr>
    <%= f.hidden_field :theme_id, {:value =>  @theme_id} %>
    <tr><td></td><td><%= f.submit %></td></tr>
  </table>
<% end %>
<%
=end
%>

<%= form_for(@comment, :url=>theme_comments_path) do |f| %>
  <table>
    <tr><td>Your Name : </td><td><%= f.text_field :c_orner, { size: 30 } %></td></tr>
    <tr><td>Subject : </td><td><%= f.text_field :c_title , { size: 30 } %></td></tr>
    <tr><td>Cooment : </td><td><%= f.text_area :c_body , { cols: 50, rows: 5 } %></td></tr>
    <%= f.hidden_field :theme_id, {:value => params[:theme_id]} %>
    <tr><td></td><td><%= f.submit %></td></tr>
  </table>
<% end %>

app/views/comments/show.html.erb
<h2>Thank you for your comment!</h1>

<% @all_comments.each do |com| %>
<ul>
<li><%= com.c_title %></li>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bbs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/themes/create.html.erb
<h1>Themes#create</h1>
<p>Find me in app/views/themes/create.html.erb</p>

app/views/themes/edit.html.erb
<h1>Themes#edit</h1>
<p>Find me in app/views/themes/edit.html.erb</p>

app/views/themes/index.html.erb
<h2>Theme List</h2>
<hr />
<%= link_to "Create New Theme", action: "new" %><br /><br />

<table>

  <tr>
    <th>id</th>
    <th>Theme</th>
    <th>orner</th>
    <th>date</th>
  </tr>

  <% @themes.each do |t| %>
    <tr>
      <td><%= t.id %></td>
      <td><%= link_to "#{t.title}", {action: "show", id: "#{t.id}"} %></td>
      <td><%= t.orner %></td>
      <td><%= t.created_at.to_s(:long) %></td>
    </tr>
  <% end %>
</table>

app/views/themes/new.html.erb
<h1>Create New Theme</h1>

<% if @theme.errors.any? %>
  <div>
    <h2><%= pluralize(@theme.errors.count, "error") %> prohibited this Theme from being saved:</h2>
    <ul>
      <% @theme.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for (@theme) do |f| %>
  <table>
    <tr><td>Your Name : </td><td><%= f.text_field :orner, { size: 30 } %></td></tr>
    <tr><td>Theme Title : </td><td><%= f.text_field :title , { size: 30 } %></td></tr>
    <tr><td>Description : </td><td><%= f.text_area :body , { cols: 50, rows: 5 } %></td></tr>
    <tr><td></td><td><%= f.submit %></td></tr>
  </table>
<% end %>

app/views/themes/show.html.erb
<h2>Theme : <%= @theme.title %></h2>
created at <%= @theme.created_at.to_s(:long) %> --  by <font color="blue"><%= @theme.orner %></font>
<hr />
Description : <%= @theme.body %><br /><br />
[<%= link_to "Add Comment", new_theme_comment_path(params[:id]) %>]<br />
<hr />

<%= @num %><br /><br /><br />

<% @comments.each do |comment| %>
  <table width="800">
    <tr bgcolor="#ccc"><td>[<%= comment.id %>] <b><%= comment.c_title %></b> posted by <font color="blue"><%= comment.c_orner %></font>  /  <%= comment.created_at %></td></tr>
    <tr bgcolor="#eee"><td><%= comment.c_body %></td></tr>
  </table>
  <br />
<% end %>